# Generated by Django 4.2.7 on 2025-07-21 00:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_question",
                    models.CharField(
                        choices=[
                            ("qcm", "QCM"),
                            ("vrai_faux", "Vrai/Faux"),
                            ("texte", "Réponse libre"),
                            ("numerique", "Numérique"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enonce", models.TextField()),
                ("points", models.PositiveIntegerField(default=1)),
                ("ordre", models.PositiveIntegerField()),
                ("explication", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "type_quiz",
                    models.CharField(
                        choices=[
                            ("evaluation", "Évaluation"),
                            ("certification", "Certification"),
                            ("pratique", "Pratique"),
                        ],
                        default="evaluation",
                        max_length=20,
                    ),
                ),
                ("duree_minutes", models.PositiveIntegerField(default=30)),
                (
                    "note_passage",
                    models.PositiveIntegerField(
                        default=70,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("tentatives_max", models.PositiveIntegerField(default=3)),
                ("melanger_questions", models.BooleanField(default=True)),
                ("afficher_correction", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField()),
                ("est_correcte", models.BooleanField(default=False)),
                ("ordre", models.PositiveIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="quiz.question",
                    ),
                ),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.quiz",
            ),
        ),
        migrations.CreateModel(
            name="TentativeQuiz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_tentative", models.PositiveIntegerField()),
                ("date_debut", models.DateTimeField(auto_now_add=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("reponses_donnees", models.JSONField(default=dict)),
                ("temps_ecoule", models.DurationField(blank=True, null=True)),
                ("est_valide", models.BooleanField(default=True)),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["score", "date_fin"],
                        name="quiz_tentat_score_40cabb_idx",
                    )
                ],
                "unique_together": {("quiz", "participante", "numero_tentative")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("quiz", "ordre")},
        ),
    ]
