# Generated by Django 4.2.7 on 2025-07-21 00:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["ordre"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quiz",
            },
        ),
        migrations.AlterModelOptions(
            name="reponse",
            options={
                "ordering": ["ordre"],
                "verbose_name": "Réponse",
                "verbose_name_plural": "Réponses",
            },
        ),
        migrations.AlterModelOptions(
            name="tentativequiz",
            options={
                "ordering": ["-date_debut"],
                "verbose_name": "Tentative de quiz",
                "verbose_name_plural": "Tentatives de quiz",
            },
        ),
        migrations.AlterField(
            model_name="question",
            name="enonce",
            field=models.TextField(verbose_name="Énoncé"),
        ),
        migrations.AlterField(
            model_name="question",
            name="explication",
            field=models.TextField(blank=True, verbose_name="Explication"),
        ),
        migrations.AlterField(
            model_name="question",
            name="ordre",
            field=models.PositiveIntegerField(verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="question",
            name="points",
            field=models.PositiveIntegerField(default=1, verbose_name="Points"),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.quiz",
                verbose_name="Quiz",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type_question",
            field=models.CharField(
                choices=[
                    ("qcm", "QCM"),
                    ("vrai_faux", "Vrai/Faux"),
                    ("texte", "Réponse libre"),
                    ("numerique", "Numérique"),
                ],
                max_length=20,
                verbose_name="Type de question",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="afficher_correction",
            field=models.BooleanField(
                default=True, verbose_name="Afficher la correction"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="duree_minutes",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Durée en minutes"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="melanger_questions",
            field=models.BooleanField(
                default=True, verbose_name="Mélanger les questions"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="note_passage",
            field=models.PositiveIntegerField(
                default=70,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Note de passage (%)",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="tentatives_max",
            field=models.PositiveIntegerField(
                default=3, verbose_name="Nombre maximum de tentatives"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="titre",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="type_quiz",
            field=models.CharField(
                choices=[
                    ("evaluation", "Évaluation"),
                    ("certification", "Certification"),
                    ("pratique", "Pratique"),
                ],
                default="evaluation",
                max_length=20,
                verbose_name="Type de quiz",
            ),
        ),
        migrations.AlterField(
            model_name="reponse",
            name="est_correcte",
            field=models.BooleanField(default=False, verbose_name="Réponse correcte"),
        ),
        migrations.AlterField(
            model_name="reponse",
            name="ordre",
            field=models.PositiveIntegerField(verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="reponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reponses",
                to="quiz.question",
                verbose_name="Question",
            ),
        ),
        migrations.AlterField(
            model_name="reponse",
            name="texte",
            field=models.TextField(verbose_name="Texte de la réponse"),
        ),
        migrations.AlterField(
            model_name="tentativequiz",
            name="date_debut",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de début"),
        ),
        migrations.AlterField(
            model_name="tentativequiz",
            name="date_fin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de fin"
            ),
        ),
        migrations.AlterField(
            model_name="tentativequiz",
            name="est_valide",
            field=models.BooleanField(default=True, verbose_name="Tentative valide"),
        ),
        migrations.AlterField(
            model_name="tentativequiz",
            name="numero_tentative",
            field=models.PositiveIntegerField(verbose_name="Numéro de tentative"),
        ),
        migrations.AlterField(
            model_name="tentativequiz",
            name="participante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participante",
            ),
        ),
        migrations.AlterField(
            model_name="tentativequiz",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.quiz",
                verbose_name="Quiz",
            ),
        ),
        migrations.AlterField(
            model_name="tentativequiz",
            name="reponses_donnees",
            field=models.JSONField(
                default=quiz.models.default_empty_dict, verbose_name="Réponses données"
            ),
        ),
        migrations.AlterField(
            model_name="tentativequiz",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Score (%)",
            ),
        ),
        migrations.AlterField(
            model_name="tentativequiz",
            name="temps_ecoule",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Temps écoulé"
            ),
        ),
    ]
